services:
  webserver:
    image: nginx:alpine
    container_name: simple_webserver
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP Router - Redirects to HTTPS
      - "traefik.http.routers.webserver-http.rule=Host(`${DOMAIN_DEMO}`)" # CHANGE THIS
      - "traefik.http.routers.webserver-http.entrypoints=web"
      - "traefik.http.routers.webserver-http.middlewares=redirect-to-https"
      # HTTPS Router
      - "traefik.http.routers.webserver-https.rule=Host(`${DOMAIN_DEMO}`)" # CHANGE THIS
      - "traefik.http.routers.webserver-https.entrypoints=websecure"
      - "traefik.http.routers.webserver-https.tls=true"
      - "traefik.http.routers.webserver-https.tls.certresolver=cloudflare"
      # Middleware for redirection
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    volumes:
      - "./index.html:/usr/share/nginx/html/index.html"
    networks:
      - traefik_net

networks:
  traefik_net:
    name: traefik_net
    external: true
